### ISSUE TITLE
Provide mirror client for testing

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/dotnet-nats-template#215]
#### Reason/Context
Similar to ts-nats-template, providing a mirroring client for testing purposes really speeds up the development of testing.

1. Add a folder in `./template/AsyncapiNatsClient` called `mirror`.
2. Copy the [regular client file](https://github.com/asyncapi/dotnet-nats-template/blob/master/template/AsyncapiNatsClient/Client.cs.js) into the new directory
3. Switch any time `publish` and `subscribe` is used from the AsyncAPI file, to create an opposite/mirror client.
4. Use the new namespace `Asyncapi.Nats.Client.Mirror` for the `Client` file.
5. Add a folder in `./template/AsyncapiNatsClient/mirror` called `channel`
6. Copy the [regular channel file](https://github.com/asyncapi/dotnet-nats-template/blob/master/template/AsyncapiNatsClient/channels/%24%24channel%24%24.cs.js) into the new directory
7. Switch any time `publish` and `subscribe` is used from the AsyncAPI file, to create an opposite/mirror channel than what is expected.
8. Use the new namespace `Asyncapi.Nats.Client.Mirror.Channels` for the `channels` file.
8. Switch the namespace for channels to `Asyncapi.Nats.Client.Mirror.Channels`, https://github.com/asyncapi/dotnet-nats-template/blob/93460200a315102b252a5a9fbf3bd98f4474aa75/template/AsyncapiNatsClient/Client.cs.js#L64

That should be it, feel free to reach out on slack or here if you have any questions!

**Comment by sambhavgupta0705** [comment]
Hi @jonaslagoni is this still up for take?
