### ISSUE TITLE
Update to version 1.0.1 of Nats.net 

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/dotnet-nats-template#293]
#### Reason/Context
We should update the NATS library version to the newest. There are no breaking changes as far as I can see. This means we can simply update the version for the library here: https://github.com/asyncapi/dotnet-nats-template/blob/93460200a315102b252a5a9fbf3bd98f4474aa75/template/AsyncapiNatsClient/AsyncapiNatsClient.csproj.js#L42
 
It needs to be updated to the following:

```csharp
    <PackageReference Include="NATS.Client" Version="1.0.1" />
```

**Comment by Ciggzy1312** [comment]
Seems like a good starting point
I can give this a try

**Comment by jonaslagoni** [comment]
@Ciggzy1312 did you have time to look into it? 🙂

**Comment by Ciggzy1312** [comment]
`<PackageReference Include="NATS.Client" Version="1.0.1" />`

Seems like changes are already made

If there is anything else I can look into, feel free to let me know :)

**Comment by jonaslagoni** [comment]
Oh, yea you are right 🧐 

Maybe https://github.com/asyncapi/dotnet-nats-template/issues/214 could be something? 🙂
